T = {
    "en": {
        "welcome":          "👋 *Welcome to MUYA_NET Bot!*\n\nFind jobs from trusted platforms.\nChoose your language:",
        "main_menu":        "🏠 *Main Menu*\n\nWhat would you like to do?",
        "browse":           "Browse jobs",
        "search":           "search jobs",
        "online":           "online work",
        "alerts":           "my alerts",
        "mycv":             "my cv",
        "lang":             "change language",
        "cats_title":       "📂 *Job Categories*\n\nChoose a category:",
        "no_jobs":          "😔 No jobs in this category right now.\n\nCheck back soon!",
        "no_cats":          "😔 No categories available yet.",
        "search_prompt":    "🔍 *Search Jobs*\n\nType a keyword:\n_(e.g. accountant, nurse, engineer, developer )_",
        "no_results":       "😔 No jobs found for *{q}*\n\nTry a different keyword.",
        "found":            "🔍 Found *{n}* jobs matching *{q}*:",
        "alert_title":      "🔔 *My Alerts*\n\nGet notified when new jobs match your interests.",
        "sub_cat":          "📂 Subscribe to Category",
        "add_kw":           "🔑 Add Keyword Alert",
        "my_subs":          "📋 My Subscriptions",
        "kw_prompt":        "🔑 *Add Keyword Alert*\n\nType a keyword:\n_(e.g. manager, developer, engineer,Accountant )_",
        "kw_saved":         "✅ Keyword Alert for *{kw}* saved!",
        "kw_exists":        "⚠️ Keyword Alert for *{kw}* is already configured.",
        "sub_saved":        "✅ Subscribed to category *{cat}*!",
        "sub_exists":       "⚠️ You are already subscribed to *{cat}*.",
        "no_subs":          "📋 You don't have any active subscription alerts configured yet.",
        "unsub_done":       "❌ Unsubscribed from *{cat}*.",
        "cv_title":         "📄 *My CV Engine*",
        "create_cv":        "✏️ Create / Edit CV",
        "view_cv":          "My cv",
        "match":            "🎯 Match My CV",
        "cv_q1":            "✏️ *CV Engine — Step 1 of 9*\n\nEnter your *Full Name*:\n_(e.g. kalkidan bereket)_",
        "cv_q2":            "✏️ *CV Engine — Step 2 of 9*\n\nEnter your *Email address*:\n_(e.g. example@gmail.com)_",
        "cv_q3":            "✏️ *CV Engine — Step 3 of 9*\n\nEnter your *Phone number*:\n_(e.g. 091234...)_",
        "cv_q4":            "✏️ *CV Engine — Step 4 of 9*\n\nEnter your current *Location (City)*:\n_(e.g. addis abeba)_",
        "cv_q5":            "✏️ *CV Engine — Step 5 of 9*\n\nProvide a short *Professional Summary*:\n_(e.g. 2-3 sentences about yourself)_",
        "cv_q6":            "✏️ *CV Engine — Step 6 of 9*\n\nList your *Education* credentials:\n_(e.g. BSc Accounting, example university, 2020)_",
        "cv_q7":            "✏️ *CV Engine — Step 7 of 9*\n\nList your professional *Work Experience*:\n_(e.g. Accountant at example company , 2021-2024)_",
        "cv_q8":            "✏️ *CV Engine — Step 8 of 9*\n\nList your specialized *Skills*:\n_(e.g. Excel, Python, Communication )_",
        "cv_q9":            "✏️ *CV Engine — Step 9 of 9*\n\nList your spoken *Languages*:\n_(e.g. Amharic, English )_",
        "cv_saved":         "✅ *CV Profile Captured Successfully!*\n\nPress *Match My CV* to scan current data configurations for openings.",
        "cv_none":          "📄 No CV document log found on file.",
        "matching":         "🎯 *Scanning structural configurations for job profiles...*",
        "top_matches":      "🎯 *Top Verified Job Profile Fits for You:*",
        "no_matches":       "😔 No automatic data fits found. Try expanding your skills matrix array.",
        "back":             "⬅️ Back",
        "apply":            "🔗 Apply Here",
        "track":            "👁 Track Status",
        "open":             "✅ Open",
        "closed":           "❌ Closed",
        "online_title":     "💻 *online work*\n\nEarn money digitally. Select a platform class:",
        "online_freelance": "💼 Freelance",
        "online_remote":    "🌍 Remote Jobs",
        "online_airdrop":   "🪂 Crypto Airdrops",
        "online_microtask": "⚙️ Microtasks",
        "online_survey":    "📊 Surveys",
        "online_youtube":   "🎬 Content Earning",
        "video_guide":      "help",
        "share_bot":        "share bot",
        "watch_video":      "🎬 Watch Tutorial Video",
        "open_link":        "🔗 Open link",
        "app_saved":        "✅ Application entry added to tracking data table.",
        "listings_end":     "🏁 End of available record logs."
    },
    "am": {
        "welcome":          "👋 *እንኳን ወደ MUYA_NET በሰላም መጡ!*\n\nFind jobs from trusted platforms.\nቋንቋ ይምረጡ:",
        "main_menu":        "🏠 ዋና መምረጫ\n\nምን ማድረግ ይፈልጋሉ?",
        "browse":           "ሥራዎችን በዘርፉ ይፈልጉ",
        "search":           "ሥራ ፈልግ",
        "online":           "የ በየነ-መረብ ስራዎች",
        "alerts":           "የኔ ማስወቂያዎች",
        "mycv":             "📄 የእኔ ሲቪ (CV)",
        "lang":             "🌐 ቋንቋ ቀይር",
        "cats_title":       "📂 *የሙያ ዘርፉን ይምረጡ*\n\nምድብ ይምረጡ:",
        "no_jobs":          "😔 በአሁኑ ጊዜ በዚህ ምድብ ውስጥ ምንም ክፍት ስራ የለም።",
        "no_cats":          "😔 ምንም የስራ ምድቦች አልተገኙም።",
        "search_prompt":    "🔍 *ሥራ ፈልግ*\n\nየመፈለጊያ ቃል ያስገቡ:\n_(ምሳሌ: accountant, nurse, engineer, developer)_",
        "no_results":       "😔 ከ *{q}* ጋር የተያያዘ ምንም ስራ አልተገኘም።",
        "found":            "🔍 ከ *{q}* ጋር የሚዛመዱ *{n}* ስራዎች ተገኝተዋል:",
        "alert_title":      "🔔 *የስራ ማስታወቂያዎች*\n\n የስራ እድሎች ሲወጡ ወዲያውኑ መልእክት ይደርስዎታል።",
        "sub_cat":          "📂 በምድብ ተከታተል",
        "add_kw":           "🔑 በቁልፍ ቃል ተከታተል",
        "my_subs":          "📋 የክትትል ዝርዝሮቼ",
        "kw_prompt":        "🔑 *በቁልፍ ቃል ለመከታተል*\n\nየመፈለጊያ ቃል ያስገቡ:\n_(ምሳሌ: manager, developer, engineer,Accountant)_",
        "kw_saved":         "✅ የቁልፍ ቃል ክትትል ለ *{kw}* ተቀምጧል!",
        "kw_exists":        "⚠️ ይህ ቁልፍ ቃል አስቀድሞ በክትትል ዝርዝርዎ ውስጥ አለ።",
        "sub_saved":        "✅ የ ምድብ *{cat}* ክትትል ተጀምሯል!",
        "sub_exists":       "⚠️ ይህ ምድብ አስቀድሞ በክትትል ዝርዝርዎ ውስጥ ይገኛል።",
        "no_subs":          "📋 ምንም ንቁ የክትትል ማስታወቂያዎች አላዘጋጁም።",
        "unsub_done":       "❌ ከ *{cat}* ክትትል ወጥተዋል።",
        "cv_title":         "📄 *የሲቪ (CV) መገንቢያ ሞጁል*",
        "create_cv":        "✏️ ሲቪ ፍጠር / አሻሽል",
        "view_cv":          "የእኔን ሲቪ አሳይ",
        "match":            "🎯 ከሲቪዬ ጋር አዛምድ",
        "cv_q1":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 1 ከ 9*\n\nሙሉ ስምዎን ያስገቡ:\n_( ለምሳሌ: ቃልኪዳን በረከት)_",
        "cv_q2":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 2 ከ 9*\n\nየኢሜል አድራሻዎን ያስገቡ:\n_( ለምሳሌ: example@gmail.com)_",
        "cv_q3":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 3 ከ 9*\n\nየስልክ ቁጥርዎን ያስገቡ:\n_( ለምሳሌ: 091234....)_",
        "cv_q4":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 4 ከ 9*\n\nአሁን ያሉበትን ቦታ (ከተማ፣) ያስገቡ:\n_(ለምሳሌ : አዲስ አበባ)_",
        "cv_q5":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 5 ከ 9*\n\nስለ እርስዎ ሙያዊ ማጠቃለያ በአጭሩ ይጻፉ:\n_( ስለ ችሎታዎ እና ፍላጎትዎ ከ2-3 ዓረፍተ ነገር )_",
        "cv_q6":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 6 ከ 9*\n\nየትምህርት ደረጃዎን ያስገቡ:\n_(ለምሳሌ: BA in Management, example university , 2021)_",
        "cv_q7":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 7 ከ 9*\n\nየስራ ልምድዎን ይዘርዝሩ:\n_(ለምሳሌ: Senior Officer at .examplecompany , 2 years)_",
        "cv_q8":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 8 ከ 9*\n\nያሉዎትን ክህሎቶች (Skills) ያስገቡ:\n_( ምሳሌ: Excel, Python, Communication)_",
        "cv_q9":            "✏️ *የሲቪ ማዋቀሪያ — ደረጃ 9 ከ 9*\n\nየሚናገሯቸውን ቋንቋዎች ያስገቡ:\n_( ምሳሌ:Amharic, English)_",
        "cv_saved":         "✅ *የሲቪ መረጃዎ በተሳካ ሁኔታ ተቀምጧል!*\n\nከእርስዎ ሲቪ ጋር የሚዛመዱ ስራዎችን ለማየት *ከሲቪዬ ጋር አዛምድ* የሚለውን ይጫኑ።",
        "cv_none":          "📄 ምንም የተቀመጠ የሲቪ ፋይል የለም።",
        "matching":         "🎯 *ከእርስዎ ሲቪ ጋር የሚስማሙ ስራዎችን በመፈለግ ላይ...*",
        "top_matches":      "🎯 *ለእርስዎ ተስማሚ የሆኑ ስራዎች:*",
        "no_matches":       "😔 ተስማሚ ስራ አልተገኘም። እባክዎ በሲቪዎ ላይ ተጨማሪ ክህሎቶችን ያክሉ።",
        "back":             "⬅️ ተመለስ",
        "apply":            "🔗 አሁን ያመልክቱ",
        "track":            "👁 ተከታተል",
        "open":             "✅ ክፍት",
        "closed":           "❌ ዝግ",
        "online_title":     "💻 *online work*\n\nበኢንተርኔት አማካኝነት ገቢ የሚያገኙባቸው መንገዶች። ምድብ ይምረጡ:",
        "online_freelance": "💼 ፍሪላንስ (Freelance)",
        "online_remote":    "🌍 የርቀት ስራዎች",
        "online_airdrop":   "🪂 የክሪፕቶ ኤርድሮፕ",
        "online_microtask": "⚙️ ማይክሮ ታስኮች",
        "online_survey":    "📊 ሰርቬይ (ጥናቶች)",
        "online_youtube":   "🎬 የቪዲዮ ይዘት ማግኛ",
        "video_guide":      "እርዳታ",
        "share_bot":        "ቦቱን ያጋሩ",
        "watch_video":      "🎬 ስለ ቦቱ ግልፅ የሆነ የቪዲዮ መመሪያችንን ይመልከቱ👇!",
        "open_link":        "🔗 ሊንኩን ክፈት",
        "app_saved":        "✅ የስራ ማመልከቻዎ በክትትል ሰንጠረዥ ውስጥ ተመዝግቧል።",
        "listings_end":     "🏁 የዝርዝር መዝገቦች ፍጻሜ።"
    }
}

def t(lng, key, **kwargs):
    dct = T.get(lng, T["en"])
    string = dct.get(key, T["en"].get(key, key))
    if kwargs:
        return string.format(**kwargs)
    return string
